[colors.primary]
background = '#191114'
foreground = '#eedfe3'

[colors.selection]
text = '#eedfe3'
background = '#6e334f'

[colors.cursor]
text = '#191114'
cursor = '#feb0d1'

[colors.normal]
black   = '#191114'
red     = '#ff7279'
green   = '#a0fe7f'
yellow  = '#ffe172'
blue    = '#f198be'
magenta = '#75334f'
cyan    = '#feb0d1'
white   = '#ffeff6'

[colors.bright]
black   = '#a5989d'
red     = '#ff9fa4'
green   = '#bcffa5'
yellow  = '#ffeca5'
blue    = '#ffbcd8'
magenta = '#ffc8df'
cyan    = '#ffdbea'
white   = '#fff8fb'
